//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHomework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kisi
    {
        public int ID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public Nullable<int> YAS { get; set; }
        public string MEMLEKET { get; set; }
        public string ADRES { get; set; }
        public string TELEFON { get; set; }
        public string EMAIL { get; set; }
    }
}
